#!/bin/bash
#version 2.0
#use like this on the client of which the public facing IP might change: ./ipchange location 
#or ./ipchange location2
# the location should match with the hostname you want to change at your DNS server

if [ $# != 1 ]
then
 echo Error: Usage ./ipchange muizen or ./ipchange diegem
 exit 2
fi

ip=`wget -O- http://www.whatip.org 2> /dev/null | grep -i "Your IP Address Is" | awk -F\> '{ print $3 }' | sed sT\</fontTT`
oldip=`cat /tmp/oldip`

if [ "$ip" != "$oldip" ]
then
 ssh root@m1.linuxbe.com  "/newdns.sh $1 $ip" 
 echo $ip >  /tmp/oldip
fi
